### ISSUE TITLE
unable to query "scissor"

### ISSUE THREAD

**Issue by darkgeek** [Konyaco/CollinsDictionary#22]
Hi,

Seems like the word "scissor" can not be queried:
![Screenshot_20230308-224328_Trebuchet](https://user-images.githubusercontent.com/1317617/223744026-2692d59b-55d8-4bc9-9361-a4c598dd2fa0.png)
while other words are ok:
![Screenshot_20230308-224353_Trebuchet](https://user-images.githubusercontent.com/1317617/223744160-68943ac5-34f6-449f-8d04-7fe8e5ed3a67.png)
I can confirm it's not a network isseue. I use Android 13, and my app is 1.4.6 installed from F-Droid.

**Comment by 123Duo3** [comment]
That's because we only support COBUILD currently. The word "scissor" only has entity in British and American Dictionaries, which we haven't support yet. 

If you meant this thingy → ✂️, it's always in plural form "scissors".
