### ISSUE TITLE
Android: F-Droid Release

### ISSUE THREAD

**Issue by realmain** [Konyaco/CollinsDictionary#4]
It would be nice if it can be added to the official [F-Droid](https://f-droid.org/) repo. It would assist in getting more visibility on this app as well.

[This is the inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) that must be met to be able to submit. More info about submitting can be [found here](https://f-droid.org/en/contribute/).

[Here is the issue tracker](https://gitlab.com/fdroid/rfp/-/issues) to request your package to be available on F-Droid. After submitting, they can assist on what is needed to be done (if anything) to get it on F-Droid.

**Comment by Konyaco** [comment]
Thank you for your suggestion. I have created a request here (https://gitlab.com/fdroid/rfp/-/issues/1999). But actually saying, this app is not stable for its mechanism. The network requests to Collins website may be blocked by cloudflare ddos protection. And I don't know if this method is granted in "Inclusion Policy".

**Comment by shuvashish76** [comment]
Now live on F-Droid app : https://www.f-droid.org/packages/me.konyaco.collinsdictionary/
_(It will take some time to show new apps on F-Droid's website)_
