### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by lokesh-krishna** [Konyaco/CollinsDictionary#6]
Sorry about hijacking the issue tracker for this but since you don't have discussions enabled on this repo, I needed a place to express my gratitude for this absolutely lovely app.  

Long have I yearned for a solid open source dictionary app and this is above and beyond anything I could have asked for. Thank you so, so much!

**Comment by Konyaco** [comment]
😄

**Comment by 123Duo3** [comment]
We've received your gratitude and are glad you enjoyed the app.
 
If you have any comments or suggestions, please feel free to ask and we will try to solve them. If not, we're sorry we're going to closing this issue.
 
BTW, since it's Lunar New Year's eve, happy new year to you!
